### ISSUE TITLE
Should new ballot/vote be a new contract or just a function?

### ISSUE THREAD

**Issue by fmatan** [daostack/daostack#10]
In the suggested scheme making a new ballot to vote on amounts to deploying a new contract. However, it can also be implemented (as in [TheDAO](https://github.com/slockit/DAO/blob/develop/DAO.sol)) as a function inside a DAO contract. Should understand what's the main differences and what's better. Moreover, right now we have no DAO contract, but only a Token and Reputation contract, and Ballots to modify them. We do need to tie each Reputation contract to a Token contract 1-1, but do we need a central DAO contract? More generally it'd be useful to define the general architecture for the entire DAO and then implement its elements. A WIP on this can be found [here](https://drive.google.com/file/d/0Bw-uTgYtnb2wZGEta2dhbUdCQmM/view?usp=sharing).

**Comment by jellegerbrandy** [comment]
the link to the "WIP" is not working for me (also I don't know what "wip" means :-)

I'm not sure what you mean when you say "we need to tie each rep contract to a token contract 1-1". The idea with the present code is that with a rep contract, you can vote on on anything (any Ballot goes). In particular, one can control different token contracts from a single rep contract. This seems to me a good thing.

**Comment by fmatan** [comment]
Thanks, corrected the link, check it up. (WIP = work in progress.)

Means that a specific reputation system should only "rule" one specific token system. You wouldn't like one reputation system to be able of distributing tokens of another reputation system. I.e. each reputation system should have its own, single token system.

**Comment by jellegerbrandy** [comment]
As it is set up now, each token system has an (at most one) owner. That owner can be a "normal" address, but also reputation system There is nothing inherent in the code now that excludes that a rep system can control more than one token system; although a token system cannot be controlled by two different rep systems.

This situation seems to me what we want. 

(If need be, we can always write a specific subclass of reputaiton contract that are limited in what they can vote on. This could make sense from a security standpoint, I suppose.)

Regarding your diagram, the model I have in my head is like this:

* Rep contract owns token contract (ownership implies "can mint new tokens")
* Rep contract owns itself (ownership implies "can mint new rep")
* Rep contract controls token contract and itself via "Ballots"
* A ballot for example can be "vote with MWS for giving N tokens and M rep to 0x124".


This is the general schema. It can then subsequently be limited.

With regard to your point about implementing ballots as separate contracts or as an internal functinos (as in the DAO). I'd say at this stage we want to have clear, general, code, which means, for me, separating code as much as possible in independent units - the separate contract patterns fits with that. Once we have the logic in place, we can think of optimizing (which of course is Very Important on the blockchain), and we can, if we need to, if that turns out to be useful, refactor the code.
