### ISSUE TITLE
Implement reputation-weighted median (RWM) of votes

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#11]
* this should (as the code is setup now) go into Ballot.sol, in "winningProposal"
* proposals in the ballot need to be linearly ordered
* winningProposal is the median of the proposals weight by reputation of the votes

**Comment by yaronvel** [comment]
Is it safe to assume that the weights reside in a 64 bit integer?
Implement bounded gas mechanisim for WM is not trivial.
One way to tackle it is to generate a bit trie.
If one may assume that reputation is 64 bits, it could reduce the worst case gas cost by 1/4.

Anyway, it is probably doable also 256 bits.
Do you have other ideas on how to compute the weighted median?

**Comment by jellegerbrandy** [comment]
"not trivial" indeed.

I've not studied algorithms for finding the median, so I'm not sure how good we can do in principle. But the fact is that gas costs are of course a constant bound, so we are severely limited in what we can calculate.

My approach (and I ll be happy with any better idea) is to hardcode an upper bound on the number of different "options" you can vote for. (I.e. you can have a ballot where you can vote an integer between 0-100, not a ballot where you can give an arbitrary number).

Not sure how your "bit trie" would work, though.

**Comment by yaronvel** [comment]
Upped bound would indeed solve the problem. But I guess it is a design decision.

In general finding non-weighted median is easy. Just keep to min/max heaps and balance them after every vote.
But the weighted scheme is hard.

The trie scheme is to treat integers as 256 bit vector, and then form a trie.
For example, the root of the trie will say what is the weight of all votes with first bit = 0, and what is the weight of all votes with first bit = 1.
This data is maintained in every split node.
Every new vote may cause at most one split, and one would have to update the weights in the entire branch that leads to the split.
So at worst case one need roughly 256 memory reads (`SLOAD`), 256 memory writes (`STORAGEMOD`)  and a single creation of new memory (`STORAGEADD`).
Gas costs for each op are presented [here](https://docs.google.com/spreadsheets/d/1m89CVujrQe5LAFJ8-YAUCcNK950dUzMQPMJBxRtGCqs/edit).
So the total gas cost for storage operation is roughly 256(5k + 50) + 50k = 1342800.
So I guess in addition to computation costs we get around 1.5M.
This would fit in a single tx. But only 3 such txs could fit into a block.
And even in this case we would have to store the weights in 64 bit or 128 bit integer (otherwise costs are doubled).
If in addition we can assume that voting value is bounded by 2**64, then we need only 64 bit trie, and costs are cheaper with x4 factor.

**Comment by jellegerbrandy** [comment]
Ok, that looks very promising indeed. 

So, to rephrase it in my words to see if i understood what you are getting at: 

Votes are registered in a Patricia tree of "vote values", with all nodes labeled with the total weight of votes of all branches passing through that node. This makes calculating the median trivial, at the cost of raising the gas costs for registering a vote. 

1.5M to register a vote is of course not acceptable (in the current state of ethereum).  But as a general upper bound it is actually pretty good, it seems to me. Worth, at least, to play around with to see if actual gas costs are indeed in that order of estimated magnitude. 

About the precision of the reputation and voting values. For rep: I'd say 64 or 128 is good enough for our purposes - I see no problem in adjusting that. Wrt voting values: I'd find it hard to even imagine a use case where it would make sense to have more than, say, 32bit precision, if it is humans that are voting. (If we are taling about subjective judgments about "contributions", 16bits are probably already a lot))

**Comment by yaronvel** [comment]
Regarding 16/32 bits precision.
One option that Matan mentioned is to vote for how much tokens to give the contributor.
Tokens are usually divided to tiny units.
For example 2^32 wei are only 0.000000004294967296 ether.

I will try to read more on median computation.

**Comment by jellegerbrandy** [comment]
yeah, that is the main use case I am thinking of as well. It makes no sense to ask people to decide to give someone 1 wei more or less. A precision in, say, 1/1000s of ether is more than enough (or perhaps even exaggerated)

**Comment by yaronvel** [comment]
I am thinking of a different approach.
In the new approach the assumption is that number of voters is at most 500,000 (number and not total rep).
I also assume that traversing linked list of size 1000 is not expensive (in theory should be in the order of 150k gas).

I propose to keep mini skip list of two levels, where in the highest level the list size is at most 1000, and in the lower level list size is between 500 and 1000.
This link to gist code to demonstrate the concept;
https://gist.github.com/anonymous/643efc6269237eed8c9b9552e6fc601a

To reduce voting costs even further, the user can compute the predecessors of its new vote node by calling `findLevelsPointers` offchain.
In this case, voting is very cheap (though in 1 out of 1000 votes split might be required).
The problem with the offchain approach is that the list may change between calling  `findLevelsPointers` and calling `insert`.
In this case `insert` will return `false`.

Does it sound reasonable?
If so, I can continue with testing and measurements.

**Comment by jellegerbrandy** [comment]
To me it sounds quite reasonable. 

The potential weak point is the splitlevel function, as you noted as well. 
 
i really like the idea of doing expensive calculations offchain.  Here are some remarks:

- i really like the idea of off-chain calculation of "hints" to reduce gas costs. It can be easily hidden in the UI, so it is seamless for the user. 
- perhaps it is better to throw an error rather than simply returning false in case the hints given are wrong
- perhaps even better is to just set the hints to (0, 0) and do the whole calculation, in case the hints are wrong. 
- you write insert returns false if the list has changed. But it seems your code does actually better, if I understand it correctly - even if other users have inserted their votes, the hint you will have calculated will still be valid and reduce the calculation costs for inserting. (I *think*:-)

**Comment by yaronvel** [comment]
Agree with everything, beside `throw` instead of `return false`.
Throw does not allow you to log or reflect the error. In addition it will consume all your gas budget.
This is crucial espicially in our case, where the average consumption is low but the worst case consumption is much higher (e.g., when call split level).
So max gas should be high, and if we use throw it would be expensive.

Anyway, I will try to run some experiments this week and see how much gas it takes.

**Comment by leviadam** [comment]
This is no longer relevant.
Although it is funny that we keep running into similar issues :)
