### ISSUE TITLE
setScheme is reverting when input and native scheme tokens don't match

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#225]
## Introduction
I am experiencing problems with `GenesisScheme.setSchemes`.  It reverts when the input scheme token is not the same as the scheme's native token.

If I try to set a scheme creating like this, it works:

`schemeToAdd = await SchemeRegistrar.new(standardTokenMock.address, 10, accounts[0])`

(This is how it is done in the arc automated tests.)

However, if I try to set a scheme creating like this, it reverts:

`schemeToAdd = SchemeRegistrar.at((await SchemeRegistrar.deployed()).address))`

(This is how it is done in arc-js.)

First a comment:  The schemes seem to me a little less "universal" if users are required to deploy new ones (if that is indeed going to be a requirement here).  I think the arc test code should test using the all of the same techniques as are required or allowed.

## Analysis

The only difference in code between working and not working is what I gave above. So, more specifically, what are the material differences?

It seems to be in the parameters that are given in the respective schemes' constructor.

In the non-functioning code, the originally-deployed schemes (created during migration) have a different fee amount, expressed clearly in Wei, and the beneficiary is the DAOstack avatar.

In the functioning test code (that does the `.new`) the new schemes have a significantly different fee amount (primarily, it is not in Wei) and the beneficiary is account[0].

(_I'm curious who the beneficiary is typically meant to be in the general real-world case.  It seems that if one wants to change the scheme's token, fee or beneficiary, then one will be forced to create a new instance of the scheme, rather than being able to reuse the Daostack instance.  What is the correct pattern meant to be here?_)

setSchemes does the following:

`controller.externalTokenIncreaseApproval(_token[i], scheme, fee);`

This is telling the token that msg.sender is authorized to cause the scheme to transfer an amount of the token equal to the fee.  The token receiving the authorization in this case is the one that is passed-in to setSchemes.  

In the working case, this token is equal to the scheme's native token.  In the non-working case, the scheme's native token and the one passed-into setSchemes are different.  Thus in the non-working case I would expect `controller.externalTokenIncreaseApproval` not to be effective.  **This looks like a problem with the Arc API.  Why not just have setSchemes automatically use the scheme's native token rather than allowing the user to pass in a different token that would fail.  Either that, or add token as a parameter to registerOrganization**

Next, setSchemes invokes `scheme.RegisterOrganization`, which does this:

`nativeToken.transferFrom(_avatar, beneficiary, fee)`

If I understand correctly:

This transfers the fee, in the scheme's native token, from the avatar to the scheme's beneficiary.  The avatar must pay for scheme registration (_but typically, in the real world, pay whom?_)

That is what we want, **but we should be using the token that was authorized by externalTokenIncreaseApproval.**

In the functioning code the beneficiary is accounts[0], so the avatar is paying accounts[0].  Further, the token that was authorized is the same as the scheme's native token.  All seems good.
 
In the non-functioning code the beneficiary is the Daostack avatar.  Thus the new avatar appears to be paying the Daostack avatar.  This seems reasonable.

**Comment by orenyodfat** [comment]
> First a comment: The schemes seem to me a little less "universal" if users are required to deploy new ones (if that is indeed going to be a requirement here). I think the arc test code should test using the all of the same techniques as are required or allowed.

-schemes are universal in a sense that same scheme can serve multiple avatars (orgs).
-Lets call USERS - ORGS_CREATORS (the ones which create orgs and attached schemes to it).
-ORGS_CREATORS are not require to deploy new scheme. they just use it as a component attached to theirs organization.
-ORGS_CREATORS does not require to call 'deploy' or 'new' for schemes.
-ORGS_CREATORS should get the instance of a scheme by using SCHEME.at((await SCHEME.deployed()).address)) 
-SCHEMES_CREATORS should deploy scheme and call its constructor with its params.
 - in order to test different schemes instances ,arc test code usually first deploy the scheme (using new)..and then tries to call its functions.

Now, when you are doing 

> schemeToAdd = SchemeRegistrar.at((await SchemeRegistrar.deployed()).address))
You get the default instance of the scheme which was deployed by the migration process.
this was deployed with different token.
In order to register your organization to this scheme you need to pay with the token that this scheme is working with.This is the reason you are reverting i guess ..which is not a bug in arc.

- In arc-js there should be  a preliminary process of deploying the universal schemes (with DAOStack native token as the payment token ,and DAOStack as the beneficiary , not sure about the fee).
-Then the ORGS_CREATORS should have the option to choose which schemes to use ,they can choose DAOStack schemes or other schemes..
-Then you can use 'at' to get the instance of the needed scheme.

**Comment by dkent600** [comment]
Thanks @orenyodfat 

> In order to register your organization to this scheme you need to pay with the token that this scheme is working with

I hope we will document this if the requirement is retained, but I have a question about it:

Why do we require that the token address be passed into setSchemes if we are only ever going to use scheme.nativeToken() ?

Side, but pertinent question:  Can setSchemes be used to add non-Arc schemes?  If so, then I expect we would need a token address passed-into setSchemes, but only then, if I am understanding.  Can setSchemes check for this case?

> ORGS_CREATORS should get the instance of a scheme by using SCHEME.at((await SCHEME.deployed()).address))

This isn't working even when I pass in the correct token.  See #226

> In arc-js there should be a preliminary process of deploying the universal schemes (with DAOStack native token as the payment token ,and DAOStack as the beneficiary , not sure about the fee).

As shown by the arc test code, using .new anyone can deploy their own scheme with themselves as beneficiary, and register it with their DAO.   Is this capability intended to be allowable?

**Comment by dkent600** [comment]
Another comment:

> ORGS_CREATORS should get the instance of a scheme by using SCHEME.at((await SCHEME.deployed()).address))
> In order to register your organization to this scheme you need to pay with the token that this scheme is working with

This becomes awkward.  

STEPS:

1) Create a new DAO:

`let org = genesisScheme.forgeOrg()`

_Note the org will have a new, distinct DAOToken address_

2) get a scheme to add to the new DAO:

`let newScheme = SCHEME.at((await SCHEME.deployed()).address))`

_newScheme.nativeToken() is going to be that of Daostack.controller.nativeToken(), not the same token as the DAO that the scheme is being added-to._

This doesn't feel good to me, but I can also imagine that maybe this is the way things are designed to be.

Where it gets awkward is that when we have to call `genesisScheme.setSchemes`, we have to spend some extra lines of code grabbing the Daostack.controller.nativeToken() to pass into setSchemes.  We can't just use the native token of the DAO we just created and to which we are adding the schemes.

Maybe things are designed to be like this, but it is counter-intuitive to me, like it would be more clean if the new DAO and schemes added to it were to, by default, share the same native token.

**Comment by orenyodfat** [comment]
> Why do we require that the token address be passed into setSchemes if we are only ever going to use scheme.nativeToken() ?

right , we can get the token from the scheme it self (same as we take the fee).

> Side, but pertinent question: Can setSchemes be used to add non-Arc schemes? If so, then I expect we would need a token address passed-into setSchemes, but only then, if I am understanding. Can setSchemes check for this case?

Yes, sure , in that case you should pass isUniversal = false .
Though if it is non-arc no need to pass token because there are no fee for registration.

> ORGS_CREATORS should get the instance of a scheme by using SCHEME.at((await SCHEME.deployed()).address))
This isn't working even when I pass in the correct token. See #226

see my comment on  #226 

> In arc-js there should be a preliminary process of deploying the universal schemes (with DAOStack native token as the payment token ,and DAOStack as the beneficiary , not sure about the fee).
As shown by the arc test code, using .new anyone can deploy their own Universal scheme with themselves as beneficiary, and register it with their DAO. Is this capability intended to be allowable?

Why not ? it is a free world..
I guess that  DAOStack will have its "white list" of universal scheme which is tested and deployed by DAOStack.  

>newScheme.nativeToken() is going to be that of Daostack.avatar.nativeToken(), not the same token as the DAO that the scheme is being added-to.

newScheme.nativeToken() can be any token (ERC20) that the scheme creator would like to use.


Saying all that , I will add that we are considering to remove the registration (and the fee ) for  daostack universal scheme due to various reasons ,most of them are not related to this issue.
We plan to further investigate and discuss that next week.

**Comment by dkent600** [comment]
@orenyodfat 

> newScheme.nativeToken() can be any token (ERC20) that the scheme creator would like to use.

That's cool, the thing in my mind is that the preferred *default* may be that the token for a new DAO, and the schemes that are added to it, would share the same token.

**Comment by orenyodfat** [comment]
@dkent600 yea..possible .for DAOStack org it probably be the case.
For other orgs...maybe .

**Comment by dkent600** [comment]
Me:
>  the preferred default may be that the token for a new DAO, and the schemes that are added to it, would share the same token.

@orenyodfat :
> for DAOStack org it probably be the case.

For DAOStack org it *is* the case.  But for new DAOs that wish to reuse the Daostack org's schemes, it is not...

...unless we use `.new` rather than `SCHEME.at((await SCHEME.deployed()).address))` and manually set the token to be the one used by DAOstack.  But then one ends up deploying new scheme instances.

If we eliminate the fee/token/beneficiary on constructor params on Universal schemes, then this issue disappears.  Is that what you are contemplating?

**Comment by dkent600** [comment]
Closing as not a bug.
