### ISSUE TITLE
Importing of zeppelin-solidity contracts doesn't work when migrating from ArcJS

### ISSUE THREAD

**Issue by tibetsprague** [daostack/daostack#232]
I'm not actually sure if we should solve this from Arc or ArcJS, but right now when we try to migrate contracts from ArcJS the daostack contracts can't find the zeppelin-solidity contracts because they are not installed within the daostack-arc module. I'm sure there are many ways to solve this. Right now ArcJS is migrating by changing directory to the daostack-arc module and running truffle migrate from there. @dkent600 's current solution is to run npm install zeppelin-solidity from within the daostack-arc module first, which seems pretty weird to me. We could instead copy the contracts into ArcJS first and migrate from there, where zeppelin-solidity is already installed but I don't really like that either, and would love to remove the need to copy the contracts from Arc to ArcJS at all. Other thoughts?

**Comment by leviadam** [comment]
The problem is of course that Truffle is compiling before migrating.
I would try to make it migrate the code in the json file without recompiling.
Should research this option.

**Comment by tibetsprague** [comment]
Hmm good point, truffle shouldn't compile contracts that haven't changed but if you are on a different computer then the paths have changed and I think it will always compile everything again.

**Comment by dkent600** [comment]
@tibetsprague The zeppelin issue is already solved with the scripts in the branch https://github.com/daostack/arc-js/tree/%2317removeTestrpcDB.  One just has to follow the instructions given in package-scripts.json.  (These instructions should also be put in the README, but I don't think I've put them in yet (thought they _are_ in the alchemy README)).

@leviadam   As for compiling:  this is because of how truffle checks the dates _inside_ the json files and compares them to the date stamps on the .sol files.  I looked into that but deferred doing anything about it because I didn't have a quick solution and it wasn't crucial compared to finishing the end-to-end scripting.

**Comment by tibetsprague** [comment]
@dkent600 I know, I just don't like the solution :)

**Comment by leviadam** [comment]
Very good @dkent600. I guess we can trick truffle not to re-compile.

**Comment by dkent600** [comment]
This is no longer an issue.  We are copying the json files into arc-js and running truffle migrate from there using a hacked version of truffle that does not attempt to recompile the contracts.
