### ISSUE TITLE
Some comments on contracts code

### ISSUE THREAD

**Issue by yaronvel** [daostack/daostack#8]
I became aware of this project yesterday at a meetup where Matan presented it.
I am not sure what is the security model you have (i.e., who is malicious and who is trusted), but I thought I can give some small comments nevertheless.

1. When setting [reputation](https://github.com/daostack/daostack/blob/master/contracts/Reputation.sol#L24), there is a danger of an overflow when `totalReputation - reputation[_account] + _amount > 2**256` (note that user is free to set `_amount` to whatever value he wishes).

2. The winning proposal [function](https://github.com/daostack/daostack/blob/master/contracts/NamedProposalBallot.sol#L62) `winningProposal` is attackable. A malicious user might propose many proposals by calling `NamedProposalBallot`, which will cause `winningProposal` to run out of gas, even if the possible maximum gas is allocated for running it.
A possible fix is to update the winning proposal on the fly, whenever calling `vote` function.

I can arrange a pull request to fix these two issues if you want.
But I am still not sure I get the full picture.

**Comment by jellegerbrandy** [comment]
Thanks, yaronvel!

A pull request for the first issue you note is very welcome. Writing a test for it would even be greater :-)

For the second issue. The NamedProposalBallot code is just shameless copied from http://solidity.readthedocs.io/en/develop/solidity-by-example.html, with a bit of reputation mixed in, and i sort of trusted it because of the source :-)

That said, I am not sure I get it your issue. The contract gets instantiated with a fixed number of proposals, that cannot be changed afterwards (the "NamedProposalBallot" is the constructor function, so will only be called once, on initialization). So yes, someone may create a ballot with lots of proposals, and perhaps run out of gas determining the winning vote (she would probably run out of gas creating the thing, though). Even if that works, it would hardly constitute an "attack" - it would just be a matter of someone deploying a contract that is not working very well.

Anyway, if you want to chat, https://daostack.slack.com and ping me as @gellej.

**Comment by yaronvel** [comment]
Regarding the second item, you are right.
I didn't notice that `NamedProposalBallot` is the constructor and I thought that everyone could add a proposal.
It is still might be not an optimal design. I would expect that `winningProposal` would be called by users (and other contracts) multiple times. So low gas usage might be more desriable for `winningProposal` then to `vote`.

As for the slack, how do I get an invetation?

**Comment by jellegerbrandy** [comment]
Ah, sorry, we do not have a "get an invitation" thing set up. Send me a mail, and I'll invite you. jelle@gerbrandy.com

**Comment by jellegerbrandy** [comment]
fixed by pr/9

**Comment by jellegerbrandy** [comment]
(btw, I fixed your test for the overflow error in https://github.com/daostack/daostack/commit/13617e5eec200b484beb673c98226caba63e4076)
